### ISSUE TITLE
Bugs with list of tasks

### ISSUE THREAD

**Issue by dacap** [dacap/github-bugs#1]
Buggy list of task items:

- [ ] item a
- [ ] item b
- [ ] item c
- [ ] item d
- [ ] item a
  - [ ] item b
  - [ ] item c
  - [ ] item d

---
Raw code of the issue:

```
- [ ] item a
- [ ] item b
- [ ] item c
- [ ] item d
- [ ] item a
  - [ ] item b
  - [ ] item c
  - [ ] item d
```

**Comment by ACyphus** [comment]
- [ ] item a
- [ ] item b
- [ ] item c
- [ ] item d
- [ ] item a
  - [ ] item b
  - [ ] item c
  - [ ] item d

**Comment by dacap** [comment]
@ACyphus I've created other issue #5 with the problem and the exact text is the one in [this comment](https://github.com/dacap/github-bugs/issues/5#issuecomment-524967638):
```
Buggy list of task items:

- [ ] item a
- [ ] item b
- [ ] item c
- [ ] item d
- [ ] item a
  - [ ] item b
  - [ ] item c
  - [ ] item d
```

**Comment by dacap** [comment]
The problem is related to the non-breaking space character: https://en.wikipedia.org/wiki/Non-breaking_space

Some items have that character instead of the regular whitespace (and it looks like the copy-and-paste feature of a browser replaces that character with regular whitespace, so it's hard to reproduce this bug without having access to the real text/the non-breaking space character).

<img width="171" alt="Screen Shot 2019-08-27 at 08 34 08" src="https://user-images.githubusercontent.com/39654/63768010-7800fb00-c8a5-11e9-9d6f-930458e7051f.png">

In the screenshot ☝️ we can see the non-breaking space as an underline "`_`", and it matches the problem displayed in the [original post](https://github.com/dacap/github-bugs/issues/1#issue-475683933).
